# Generated by Django 5.0.2 on 2024-02-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_detail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='cart',
        ),
    ]
