# Generated by Django 5.0.2 on 2024-02-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('cart_detail', '0002_remove_cartdetail_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cart.cart'),
        ),
    ]
