# Generated by Django 5.0.2 on 2024-02-24 16:13

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_detail', '0003_cartdetail_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartdetail',
            options={'base_manager_name': 'sell_product_manager', 'ordering': ['-id']},
        ),
        migrations.AlterModelManagers(
            name='cartdetail',
            managers=[
                ('sell_product_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
