# Generated by Django 5.0.2 on 2024-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_status',
            field=models.BooleanField(default=False),
        ),
    ]
