# Generated by Django 5.0.2 on 2024-02-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_status',
            field=models.BooleanField(default=True),
        ),
    ]
