# Generated by Django 5.0.2 on 2024-02-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='group_id',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reply',
            name='deep',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reply',
            name='secret_reply',
            field=models.BooleanField(choices=[(True, '비밀글'), (False, '일반글')], default=False),
        ),
    ]
