# Generated by Django 5.0.2 on 2024-02-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_reply_group_id_alter_reply_deep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='deep',
            field=models.IntegerField(default=3),
        ),
    ]
