# Generated by Django 5.0.2 on 2024-02-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0003_alter_reply_deep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='deep',
            field=models.IntegerField(default=1),
        ),
    ]
