# Generated by Django 5.0.2 on 2024-02-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
